name: Fetch Comments

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - run: pip install requests

    - run: python script.py

    - name: Commit & Push
      run: |
        git config user.name "bot"
        git config user.email "bot@example.com"
        git add comments.json progress.txt
        git commit -m "update comments" || echo "no change"
        git push
